- name: Create directory for log files
  file:
    path: /var/traveloka/log/
    state: directory
    mode: u=rwx,g=rwx,o=rwx
  become: yes

- name: Create log files for CloudWatch to pick-up
  file:
    path: "/var/traveloka/log/{{ app_name }}_out.log"
    state: touch
    mode: u=rwx,g=rwx,o=rwx
  become: yes

- name: Create log files for CloudWatch to pick-up
  file:
    path: "/var/traveloka/log/{{ app_name }}_error.log"
    state: touch
    mode: u=rwx,g=rwx,o=rwx
  become: yes
